### PR TITLE
Fix d.ts generation

### LINKED ISSUE #173: Types are broken in 11.0
index.d.ts now consists of `export * from './core'`, but the package doesn't ship with `./core.d.ts` or `./lib/core.d.ts`.

Probably the right fix is to turn on `"declaration": true` in tsconfig and `export * from './lib/core'` in index.d.ts

### PR DESCRIPTION
**Pull request by sandersn**
1. Generate d.ts files for all .js files by adding `"declaration": true` in tsconfig.json.
2. In index.d.ts, export * from './lib/core' instead of './core'

Fixes #173

### CODE REVIEW

**Comment by sandersn** [comment]
CI fails because ts-loader expects a node version higher than 8.0. Pretty sure this isn't related to my change.

**Comment by sandersn** [comment]
Now CI fails saying it can't find `./lib` from `index.js`. This probably *is* a result of my change, but I'm not sure why.

**Comment by sandersn** [comment]
Oh, haha nope, #175 is also broken and does nothing but update to node 12.

**Comment by crcn** [comment]
Thanks! Should be on NPM as `11.0.11`.

**Pull request merged**
