### PR TITLE
Expose operation creator

### LINKED ISSUE #202: Discussion: abstract syntax tree
Hi Craig,

Currently, I’m working on SQL integration in CASL and I need to transform Mongo query into sql query. The standard way to do something like this is through AST. There are 2 steps:

1. Transform language into AST
2. Using Iterator or Visitor pattern walk over AST and transform it to whatever language or result you want

So, having AST of Mongo query in casl, I’ll be able to use the same pattern for 2 cases:

1. Check permissions in runtime
2. Transform permissions to any database query (other than mongo query)

To do this I need to implement just 2 separate implementations: RuntimeQueryIterator and SQLIterator

So, what do you thing?

Theoretically it should help with Async operators support as well. Your current design is quite similar to what I need the difference is that your objects currently encapsulate data (about operator) and behavior (how to apply this operator). 

I know that you refactored the whole package recently and understand that you may have own vision on siftjs future. So, feel free to decline and close this discussion.

### PR DESCRIPTION
**Pull request by crcn**
Fixes #202 

Notes:

- Exposes operations instances
- Operations now have a `name` prop that includes `$in`, `$eq`, `$lt`, etc.

Demo:

```typescript
import {createDefaultQueryOperation, createOperationTester} from "sift";
type Item = { name: string };
const operation = createDefaultQueryOperation<Item>({ name: /\w+/ });
const test = createOperationTester(operation);
test({ name: "blah" });
```

Lmk what you think of this @stalniy!

### CODE REVIEW

**Comment by stalniy** [comment]
Thanks @crcn ! I'll test it today

**Comment by stalniy** [comment]
Thanks again for quick suggestion, I really appreciate this!

After playing around with resulting operations, I see that they are very sift specific. For example, when I create operation for the next query:

```js
{
      'a.b.c': 1,
      c: { $eq: 2, $lt: 4 }
}
```

I get a function in `params` property for `c`, instead of a particular value and I need a value to generate SQL query. I can get around this by using `ownerQuery` property and parse it by myself (or `params` property of `NestedOperation`) but I don't like to do this because it feels like unfinished parsing job. 

Ideally I would like to get language agnostic AST (or something close to it). For example, the query above can be represented as:

```json
{
  "operator": "$and",
  "children": [
     { "operator": "$eq", "field": "a.b.c", "value": 1 },
     { "operator": "$eq", "field": "c", "value": 2 },
     { "operator": "$lt", "field": "c", "value": 4 },
  ]
}
```

So, then I can simply iterate over this:

```js
const operators = {
  $and(operation) {
    return operation.children
     .reduce((children, child) => children.concat(`(${toSQL(child)})`), [])
     .join(' AND ')
  },
  $eq(operation) {
     return `${operation.field} = ${operation.value}`
  },
  $lt(operation) {
    return `${operation.field} < ${operation.value}`
  }
}

function toSQL(ast) {
  return operators[ast.operator]();
}
```

And the result is:

```js
const sql = toSQL({
  "operator": "$and",
  "children": [
     { "operator": "$eq", "field": "a.b.c", "value": 1 },
     { "operator": "$eq", "field": "c", "value": 2 },
     { "operator": "$lt", "field": "c", "value": 4 },
  ]
});

console.log(sql);  // (a.b.c = 1) AND (c = 2) AND (c < 4)
```

**Comment by crcn** [comment]
```typescript
{
  "operator": "$and",
  "children": [
     { "operator": "$eq", "field": "a.b.c", "value": 1 },
     { "operator": "$eq", "field": "c", "value": 2 },
     { "operator": "$lt", "field": "c", "value": 4 },
  ]
}
```

I like this a lot, but it's very different than the current data model. At a glance it looks like this format may require a whole new refactor. That'll take some time.

I think in the meantime what I can do is come up with a function that translates mongo queries into this format. Then sometime later use this format for filtering.

**Comment by stalniy** [comment]
Yes, this format looks quite promising for me as well. Actually it can be used to represent any logical condition and can be easily translated to any language using recursive calls. I've already started playing with it and have a design for it:

1.  There are 2 types of conditions:
- `FieldCondition` - condition that depends on a field and its value and cannot be used separately (e.g., `<`, `=`)
- `CompoundCondition` - condition that does not depend on the field and value but instead represents a logical container (e.g., `AND`, `OR`, `NOT`)
2. `Parser` is responsible to parse a particular language (e.g., MongoDB) into AST format which consists of 2 types of conditions from 1
3. `Parser` has `parse` method and is configurable via `OperatorInstruction`, for each operator we need to say what is `FieldCondition` and what is `CompoundCondition`. For example:
    
    ```js
    export const $size = {
      type: FieldCondition,
      validate: ensureIs('number')
    };
    ```

    Every `OperatorInstruction` may define optional `validate`, `parse` and `build` hooks to intercept default behavior of a `Parser`
4. `Interpreter` is a thing that takes AST and interprets it some way (e.g., translates into SQL, or knex query builder, or checks values in js runtime). This is an object of operators and `interpret` method. It's completely stateless.

**Comment by stalniy** [comment]
Again, I understand this is very different from the current state of `sift.js`, so if it's not something you want sift to be I can this understand and will work on a separate library.

But if you like it, I will work on a PR to sift.

**Comment by crcn** [comment]
> Again, I understand this is very different from the current state of sift.js, so if it's not something you want sift to be I can this understand and will work on a separate library.

Totally open to new ideas 👍🏻. If you have something that you'd like to implement, I'd love to see it! The design that you proposed looks really good. 

The only thing I wonder about is whether it makes sense to include an interpreter for other languages in the library. Could that be in its own repository? E.g: `sift-interpreter`.

**Comment by stalniy** [comment]
Yes, this is very similar to what I have in mind! I thought to split the idea into this monorepo:

```
packages/
--ast (interfaces + CompoundCondition + FieldCondition + AST builder)
--mongo (parser + interpreter)
--knex (interpreter)
--sql (interpreter)
--js (interpreter)
```

AST builder is this:

```js
import { where, not } from '@sift/ast'
import { JsInterpreter } from '@sift/js'

const ast = where('a.b.c').eq(2)
  .and(where('a').lt(12))
  .and(where('b').gt(14)
const invertedAST = not(ast);

const interpreter = new JsInterpreter() 
const result = interpreter.interpret(invertedAST, { a: 12, b: 14, a: { b: { c: 2 } } });
```

In the end, `sift` will implement `JsTranslator` (or interpreter) using the same approach as with `toSQL` function we can evaluate AST using JS and check conditions on object properties.

**Comment by stalniy** [comment]
So, how do we approach this? do you plan to convert this repo to monorepo or do you want me to create a separate repo (I actually did it already in order to test the assumptions)?

You can check the intermediate results - https://github.com/stalniy/muast/blob/master/packages/mongo/src/astify.ts

**Comment by stalniy** [comment]
Further playing with different options, I think that there is no need for a separate `sift` library in the monorepo because it will a "one liner" library. Look, having `@sift/mongo` and `@sift/js` we can do this:

```js
import { Parser as MongoQueryParser, $eq, defaultParser } from '@muast/mongo'
import { JsInterpreter, eq, defaultInterpreter } from '@muast/js'

const translator = (parser, interpreter) => (query) => {
  const ast = parser.parse(query);
  return interpreter.eval.bind(interpreter, ast);
};

const sift = translator(new MongoQueryParser({ $eq }), new JsInterpreter({ $eq: eq }));
// or
const sift = translator(defaultParser, defaultInterpreter) // defaultParser and defaultInterpreter contains all operators. This is an option for those who don't care about bundle size or develop on backend
```

`translator` function can be moved into `@sift/ast` or we call it `@sift/core`.

Any thoughts on this?

**Comment by stalniy** [comment]
And to support async execution the only required thing is to implement operators for JsInterpreter that understand Promise. For example,

```js
import { JsInterpreter, asyncEq } from '@sift/js'

const asyncInterpreter = new JsInterpreter({ $eq: asyncEq });
```

**Comment by crcn** [comment]
>  I think that there is no need for a separate sift library in the monorepo because it will a "one liner" library

Some backwards compatibility for the API would be nice -- a lot of libraries use sift. Something such as `@sift/filter` should be enough.

>  do you plan to convert this repo to monorepo or do you want me to create a separate repo (I actually did it already in order to test the assumptions)?

Yep, happy to make this into a monorepo - might be a good idea to move this to an organization that has read/write access for both of us. Thoughts on that?

Everything looks great 👍🏻

**Comment by stalniy** [comment]
I have been thinking about the same but then we will have only a single monorepo there :) 

The only purpose to do this is if we are going to implement the same library in different languages (e.g., C#, Java, Swift, Kotlin, PHP, Ruby, Python, something else?)

**Comment by crcn** [comment]
Yeah good point, probably best to keep things in one spot. I'll make that conversion next week when I have more free time.

**Comment by stalniy** [comment]
Hi Craig,

I think there is no need to convert sift to monorepo as I already created one. I‘lol add you as a collaborator. Eventually, this repo may become a small library that uses several packages from that monorepo. The name of monorepo very likely will be changed(e.g., aster). 

What are you thoughts on this?

**Comment by crcn** [comment]
Yeah, if you already have the functionality done, then that makes sense to me. 👍🏻

**Comment by stalniy** [comment]
Hi @crcn,

The basic implementation is finished. It currently mimics functionality of siftjs. 

**I'm writing in order** to ask whether you interested in helping me to improve that library and whether you plan to use it to implement sift.js.

If you have free time and know some nodejs ORM/ODM, it would be very cool if you could implement one of the existing improvements (you can find them [here](https://github.com/stalniy/ucast/issues)) or propose an new implementation. All these will help eventually to integrate casl with that ORMs.

**Comment by crcn** [comment]
Hey @stalniy, not right now, my hands a super full with other things. I'll definitely keep an eye on your library though.

**Pull request merged**
